In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

wine = pd.read_csv('https://bit.ly/wine_csv_data')

data = wine[['alcohol', 'sugar', 'pH']].to_numpy()
target = wine['class'].to_numpy()

train_input, test_input, train_target, test_target = train_test_split(data, target, test_size=0.2, random_state=42)

In [3]:
#랜덤포레스트 구현
from sklearn.model_selection import cross_validate
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_jobs=-1, random_state=42)
scores = cross_validate(rf, train_input, train_target,return_train_score=True, n_jobs=-1)


In [5]:
print(np.mean(scores['train_score']))
print(np.mean(scores['test_score']))

0.9973541965122431
0.8905151032797809


In [6]:
#특성 중요도
rf.fit(train_input, train_target)
print(rf.feature_importances_)

[0.23167441 0.50039841 0.26792718]


In [10]:
#OOB샘플
rf=RandomForestClassifier(oob_score=True, n_jobs=-1, random_state=42)
rf.fit(train_input, train_target)
print(rf.oob_score_)
print(rf.feature_importances_)

0.8934000384837406
[0.23167441 0.50039841 0.26792718]


In [13]:
#엑스트라 트리
from sklearn.ensemble import ExtraTreesClassifier
et = ExtraTreesClassifier(n_jobs=-1, random_state=42)
scores = cross_validate(et, train_input, train_target,return_train_score=True, n_jobs=-1)
et.fit(train_input, train_target)

print(np.mean(scores['train_score']))
print(np.mean(scores['test_score']))
print(et.feature_importances_)

0.9974503966084433
0.8887848893166506
[0.20183568 0.52242907 0.27573525]


In [20]:
from sklearn.ensemble import GradientBoostingClassifier

gb = GradientBoostingClassifier(n_estimators=500, learning_rate=0.2, random_state=42)
scores = cross_validate(gb, train_input, train_target,return_train_score=True, n_jobs=-1)
gb.fit(train_input, train_target)

print(np.mean(scores['train_score']))
print(np.mean(scores['test_score']))
print(gb.score(test_input, test_target))

0.9464595437171814
0.8780082549788999
0.8707692307692307


In [23]:
from sklearn.ensemble import GradientBoostingClassifier

gb = GradientBoostingClassifier(n_estimators=500, learning_rate=0.2, subsample=0.8, random_state=42)
scores = cross_validate(gb, train_input, train_target,return_train_score=True, n_jobs=-1)
gb.fit(train_input, train_target)

print(np.mean(scores['train_score']))
print(np.mean(scores['test_score']))
print(gb.score(test_input, test_target))

0.9463633551918373
0.877815577108166
0.8730769230769231
